#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=98
USE_PROCD=1
PROG=/data/sing-box/sing-box
CONF=/data/sing-box/config.json
WORKDIR=/tmp/sing-box

start_service() {
        [ -f "$PROG" ] && {
                procd_open_instance
                procd_set_param command ${PROG} run -c ${CONF} -D ${WORKDIR}
                procd_set_param limits core="unlimited"
                procd_set_param limits nofile="1000000 1000000"
                procd_set_param respawn
                procd_close_instance
        }

}

stop_service() {
        SERVICE_SIG_STOP="KILL"
        service_stop ${PROG}

}