name: Build and Release Fyne App

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.24.1

      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Vendor dependencies
        run: |
          go mod tidy
          go mod vendor

      - name: Install fyne-cross
        run: |
          go install github.com/fyne-io/fyne-cross@latest

      - name: Build Windows App
        run: |
          fyne-cross windows -arch=amd64 -app-id=io.rd15.tool

      - name: Install GitHub CLI
        run: |
          sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create GitHub Release
        run: |
          gh release create ${{ github.ref_name }} \
          /home/runner/work/rd15tool/rd15tool/fyne-cross/dist/windows-amd64/rd15tool.exe.zip \
            --title "${{ github.ref_name }}" \
            --notes "This release was automatically generated by GitHub Actions."
